[project]
name = "fitness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.5.0",
    "questionary>=2.1.1",
    "rich>=14.2.0",
    "streamlit>=1.51.0",
]
